Models/Book.cs
using System;
using System.Collections.Generic;

namespace LMS.Models
{
    public partial class Book
    {
        public Book()
        {
            BookDetails = new HashSet<BookDetail>();
            BorrowRecords = new HashSet<BorrowRecord>();
            Comments = new HashSet<Comment>();
            Authors = new HashSet<Author>();
        }

        public int Id { get; set; }
        public string Title { get; set; } = null!;
        public string? Isbn { get; set; }
        public int? Edition { get; set; }
        public string? Publisher { get; set; }
        public string? Description { get; set; }
        public string? Status { get; set; }

        public virtual ICollection<BookDetail> BookDetails { get; set; }
        public virtual ICollection<BorrowRecord> BorrowRecords { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }

        public virtual ICollection<Author> Authors { get; set; }
    }
}

Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using LMS.Services;
using LMS.Models;
using LMS.ViewModels;

namespace LMS.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookService;

        public BookController(IBookService bookService)
        {
            _bookService = bookService;
        }
        public IActionResult Index()
        {
            IEnumerable<Book> books = _bookService.GetBooks();
            return View(books);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("Title, Isbn, Edition, Publisher, Description")] Book book)
        {
            // set default status for book
            book.Status = "AVAIL";

            try
            {
                _bookService.AddBook(book);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMsg = ex.Message;
                return View();
            }


        }

        public async Task<IActionResult> Details(int id)
        {
            // get book's info from database
            Book? book = _bookService.GetBookById(id);
            if (book == null)
            {
                ViewData["ErrorMsg"] = "Error 404: Book not found";
                return View();
            }

            // Get book's meta data based on book's title
            BookMetaData? bookMetaData = await _bookService.GetBookMetaData(book.Title);

            BookDetails bookDetails = new BookDetails
            {
                BookModel = book,
                BookMetaData = bookMetaData
            };
            return View(bookDetails);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Book? book = _bookService.GetBookById(id.Value);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [HttpPost]
        public IActionResult Edit([Bind("Id, Title, Isbn, Edition, Description")] Book editBook, int id)
        {
            if (editBook.Id != id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _bookService.UpdateBook(editBook);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ViewData["ErrorMsg"] = ex.Message;
                    return View(editBook);
                }
            }
            else
            {
                return View(editBook);
            }
        }
    }
}

Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using LMS.Services;
using LMS.Models;
using System.Text.Json;

namespace LMS.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        // TODO: Need to be fix later (model binding from view not very clean)
        [HttpPost]
        public IActionResult Add(Comment comment)
        {

            // Check for user authentication
            ISession session = HttpContext.Session;
            string jsonUsr = session.GetString("loggedUser");
            User? user = null;
            if (jsonUsr != null) // user already logged in
            {
                user = JsonSerializer.Deserialize<User>(jsonUsr);
            } else // if user not login, redirect to homepage
            {
                return RedirectToAction("Index", "Home");
            }

            // setup the correct info for comment
            comment.PostTime = DateTime.Now;
            comment.Title = comment.Title;
            comment.UserId = user.Id;

            _commentService.AddComment(comment);
            return RedirectToAction("Index", "Book");
        }
    }
}

Views/Book/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Book
<h1>Create new book</h1>
<h4>@ViewBag.ErrorMsg</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Book" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edition" class="control-label"></label>
                <input asp-for="Edition" class="form-control" />
                <span asp-validation-for="Edition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Book/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model LMS.ViewModels.BookDetails;

<h1>Details book</h1>
<h2>@ViewData["ErrorMsg"]</h2>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookModel.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookModel.Title)
        </dd>

        <h4>Meta information</h4>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookMetaData.Thumbnail)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.BookMetaData.Thumbnail" asp-append-version=true/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookMetaData.PageCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookMetaData.PageCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookMetaData.PublishedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookMetaData.PublishedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookMetaData.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookMetaData.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookMetaData.MainCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookMetaData.MainCategory)
        </dd>
    </dl>
</div>

<form asp-action="Add" asp-controller="Comment" method="post">
    <input type="hidden" name="BookId" value="@Model.BookModel.Id" />
    <input type="text" name="Title" required />
    <textarea name="Text" rows="5" cols="50" placeholder="Enter your review here"></textarea>
    <br /><br />
    <input type="submit" />
</form>

<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BookModel.Id}) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Book/Edit.cshtml
@model LMS.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<h4>@ViewData["ErrorMsg"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Edition" class="control-label"></label>
                <input asp-for="Edition" class="form-control" />
                <span asp-validation-for="Edition" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Book/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Index";
}
@model IEnumerable<Book>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Isbn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Publisher)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Authors)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Isbn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Authors.Count)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                
            </td>
        </tr>
}
    </tbody>
</table>